### ISSUE TITLE
PDF conversion for the password protected doc file

### ISSUE THREAD

**Issue by krisalay** [vladgolubev/aws-lambda-libreoffice#28]
Hello,

I am trying to convert the password protected .docx file to pdf using this nodejs package.
But I am not able to figure out the way to do so. Can you please let me know the best way to achieve this functionality?

**Comment by vladgolubev** [comment]
Hey @krisalay!

I'm glad you found my package useful, but unfortunately, I haven't worked with password-protected files so can't advise you on this topic.

However, if you find a way to do this from LibreOffice CLI you can pass any arguments you want to `execSync`, as all it does is wrapping original LibreOffice CLI

**Comment by krisalay** [comment]
@vladgolubev Thank you for your quick response. I will try to do it using the CLI.

**Comment by krisalay** [comment]
@vladgolubev 
I have another issue.
I am running my service in kubernetes with 32 replica sets. And I passes about 11k requests to the server for the conversion process.
For about 1.5k requests, I get the following error:

```
[Error: Command failed: /tmp/instdir/program/soffice --headless --invisible --nodefault --view --nolockcheck --nologo --norestore --convert-to pdf _local_bucket/ec805320-720d-4781-b74e-abfab751b5ed.docx --outdir _local_bucket
terminate called after throwing an instance of 'com::sun::star::lang::WrappedTargetRuntimeException'
Application Error](url)
```

Can you please let me know what the issue is?

**Comment by krisalay** [comment]
@vladgolubev  Thanks, I will look into it.

**Comment by ncruces** [comment]
About that, @vladgolubev (this only working in AWS).

First of all, thanks for this package. Helped me tremendously.
I've been meaning to say this, and wasn't sure where.

I can report that this package works out-of-the-box in [Google Cloud Functions](https://cloud.google.com/functions/) (and I imagine [Firebase](https://firebase.google.com/docs/functions/)), as long as I select the beta [Node.js 8 runtime](https://cloud.google.com/functions/docs/concepts/nodejs-8-runtime) (because of #15).

I'm using a 2048MB/2.4GHz _“VM”_, but the 1024MB/1.4GHz would do as well.

**Comment by vladgolubev** [comment]
Thanks for the info @ncruces! I'll add this to `README`

**Comment by ncruces** [comment]
Package as changed since I've used it last. I don't use this out-of-the-box any more. I also don't recognize that error message.

Things to look for: are you using Node.js 8 Beta?
Do you have sufficient memory to deploy this (you need at least 1 GB)?

I'm using the same LibreOffice binaries compiled here (lo.tar.br), so I'm sure those work. But I'm using Go instead of Node.js. Cloud Functions Go is still a closed alpha and under NDA, so it doesn't make sense to contribute my solution. I'll revisit that decision in the future. Changes I made are "documented" [here](https://github.com/vladgolubev/serverless-libreoffice/issues/4).

**Comment by eckastudio** [comment]
Thanks @ncruces for your answers !!!
I found my error ... I use a local LibreOffice on local env for testing and this awesome plugin in prod env ... Bad "if" implementation ...

And I can confirm ... the plugin is still working out-of-the-box on Cloud Functions !!! :)

Thanks to all !!!
